const { openDatabase } = require('../db/database');
const { badRequest, notFound } = require('../utils/errors');

function now() { return new Date().toISOString(); }
function text(value) { return value === undefined || value === null ? '' : String(value).trim(); }
function id(value, field = 'id') { const result = Number(value); if (!Number.isSafeInteger(result) || result < 1) throw badRequest(`${field} 必须是正整数。`, { code: 'INVALID_ID', fieldName: field }); return result; }
function map(row) { return row && ({ id: row.id, parentId: row.parentId, menuType: row.menuType, menuName: row.menuName, routePath: row.routePath, component: row.component, permissionCode: row.permissionCode, icon: row.icon, sortOrder: row.sortOrder, visible: Boolean(row.visible), status: row.status, isBuiltin: Boolean(row.isBuiltin), createdAt: row.createdAt, updatedAt: row.updatedAt }); }
function getMenuDb(db, menuId, options = {}) { const row = db.prepare(`SELECT id, parent_id AS parentId, menu_type AS menuType, menu_name AS menuName, route_path AS routePath, component, permission_code AS permissionCode, icon, sort_order AS sortOrder, visible, status, is_builtin AS isBuiltin, created_at AS createdAt, updated_at AS updatedAt FROM sys_menus WHERE id = ?`).get(menuId); if (!row && !options.optional) throw notFound('菜单不存在。', { id: menuId }); return map(row); }
function listMenus(query = {}) {
  const db = openDatabase(); try {
    const rows = db.prepare(`SELECT id, parent_id AS parentId, menu_type AS menuType, menu_name AS menuName, route_path AS routePath, component, permission_code AS permissionCode, icon, sort_order AS sortOrder, visible, status, is_builtin AS isBuiltin, created_at AS createdAt, updated_at AS updatedAt FROM sys_menus WHERE (@status = '' OR status = @status) ORDER BY COALESCE(parent_id, 0), sort_order, id`).all({ status: text(query.status) }).map(map);
    return { rows, tree: buildTree(rows) };
  } finally { db.close(); }
}
function buildTree(rows) { const byParent = new Map(); rows.forEach((row) => { const parent = row.parentId || 0; if (!byParent.has(parent)) byParent.set(parent, []); byParent.get(parent).push({ ...row, children: [] }); }); const attach = (item) => ({ ...item, children: (byParent.get(item.id) || []).map(attach) }); return (byParent.get(0) || []).map(attach); }
function normalizePayload(input, existing = {}) {
  const menuType = text(input.menuType) || existing.menuType || 'menu'; if (!['directory', 'menu', 'button'].includes(menuType)) throw badRequest('menuType 不合法。', { code: 'INVALID_MENU_TYPE' });
  const menuName = Object.prototype.hasOwnProperty.call(input, 'menuName') ? text(input.menuName) : existing.menuName; if (!menuName || menuName.length > 64) throw badRequest('menuName 为 1-64 位文本。', { code: 'INVALID_MENU_NAME' });
  const rawParent = Object.prototype.hasOwnProperty.call(input, 'parentId') ? input.parentId : existing.parentId; const parentId = rawParent === null || rawParent === '' || rawParent === undefined ? null : id(rawParent, 'parentId');
  const permissionCode = Object.prototype.hasOwnProperty.call(input, 'permissionCode') ? text(input.permissionCode) || null : existing.permissionCode || null;
  if (permissionCode && !/^[a-z][a-z0-9:_-]{2,127}$/.test(permissionCode)) throw badRequest('permissionCode 格式不合法。', { code: 'INVALID_PERMISSION_CODE' });
  const visible = Object.prototype.hasOwnProperty.call(input, 'visible') ? (input.visible ? 1 : 0) : (existing.visible ? 1 : 0);
  const sortOrder = Object.prototype.hasOwnProperty.call(input, 'sortOrder') ? Number(input.sortOrder) : (existing.sortOrder || 0); if (!Number.isSafeInteger(sortOrder)) throw badRequest('sortOrder 必须是整数。', { code: 'INVALID_SORT_ORDER' });
  const status = Object.prototype.hasOwnProperty.call(input, 'status') ? text(input.status) : existing.status || 'active'; if (!['active', 'inactive'].includes(status)) throw badRequest('status 仅支持 active 或 inactive。', { code: 'INVALID_STATUS' });
  return { parentId, menuType, menuName, routePath: Object.prototype.hasOwnProperty.call(input, 'routePath') ? text(input.routePath) || null : existing.routePath || null, component: Object.prototype.hasOwnProperty.call(input, 'component') ? text(input.component) || null : existing.component || null, permissionCode, icon: Object.prototype.hasOwnProperty.call(input, 'icon') ? text(input.icon) || null : existing.icon || null, sortOrder, visible, status };
}
function assertParent(db, menuId, parentId) { if (parentId === null) return; if (parentId === menuId) throw badRequest('菜单不能作为自身父级。', { code: 'INVALID_MENU_PARENT' }); const parent = getMenuDb(db, parentId); if (parent.menuType === 'button') throw badRequest('按钮菜单不能作为父级。', { code: 'INVALID_MENU_PARENT' }); }
function createMenu(input = {}) { const db = openDatabase(); try { const payload = normalizePayload(input); assertParent(db, null, payload.parentId); const result = db.prepare(`INSERT INTO sys_menus (parent_id, menu_type, menu_name, route_path, component, permission_code, icon, sort_order, visible, status, is_builtin, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?)`).run(payload.parentId, payload.menuType, payload.menuName, payload.routePath, payload.component, payload.permissionCode, payload.icon, payload.sortOrder, payload.visible, payload.status, now(), now()); return getMenuDb(db, result.lastInsertRowid); } catch (error) { if (/UNIQUE constraint failed: sys_menus.permission_code/.test(error.message)) throw badRequest('权限编码已存在。', { code: 'DUPLICATE_PERMISSION_CODE' }); throw error; } finally { db.close(); } }
function updateMenu(menuId, input = {}) { const db = openDatabase(); try { const existing = getMenuDb(db, id(menuId)); const payload = normalizePayload(input, existing); assertParent(db, existing.id, payload.parentId); db.prepare(`UPDATE sys_menus SET parent_id = ?, menu_type = ?, menu_name = ?, route_path = ?, component = ?, permission_code = ?, icon = ?, sort_order = ?, visible = ?, status = ?, updated_at = ? WHERE id = ?`).run(payload.parentId, payload.menuType, payload.menuName, payload.routePath, payload.component, payload.permissionCode, payload.icon, payload.sortOrder, payload.visible, payload.status, now(), existing.id); return getMenuDb(db, existing.id); } catch (error) { if (/UNIQUE constraint failed: sys_menus.permission_code/.test(error.message)) throw badRequest('权限编码已存在。', { code: 'DUPLICATE_PERMISSION_CODE' }); throw error; } finally { db.close(); } }
function setMenuStatus(menuId, status) { return updateMenu(menuId, { status }); }
function deleteMenu(menuId) { const menu = id(menuId); const db = openDatabase(); try { const existing = getMenuDb(db, menu); if (existing.isBuiltin) throw badRequest('内置菜单不可删除。', { code: 'BUILTIN_MENU_PROTECTED' }); const childCount = db.prepare('SELECT COUNT(*) AS total FROM sys_menus WHERE parent_id = ?').get(menu).total; const roleCount = db.prepare('SELECT COUNT(*) AS total FROM sys_role_menus WHERE menu_id = ?').get(menu).total; if (childCount || roleCount) throw badRequest('菜单仍有关联子菜单或角色授权，不能物理删除；请停用。', { code: 'MENU_HAS_ASSOCIATIONS', childCount, roleCount }); db.prepare('DELETE FROM sys_menus WHERE id = ?').run(menu); } finally { db.close(); } }
function getUserMenus(userId) { const db = openDatabase(); try { const rows = db.prepare(`SELECT DISTINCT m.id, m.parent_id AS parentId, m.menu_type AS menuType, m.menu_name AS menuName, m.route_path AS routePath, m.component, m.permission_code AS permissionCode, m.icon, m.sort_order AS sortOrder, m.visible, m.status, m.is_builtin AS isBuiltin, m.created_at AS createdAt, m.updated_at AS updatedAt FROM sys_menus m JOIN sys_role_menus rm ON rm.menu_id = m.id JOIN sys_user_roles ur ON ur.role_id = rm.role_id JOIN sys_roles r ON r.id = ur.role_id WHERE ur.user_id = ? AND m.status = 'active' AND m.visible = 1 AND r.status = 'active' ORDER BY COALESCE(m.parent_id, 0), m.sort_order, m.id`).all(userId).map(map); return buildTree(rows.filter((row) => row.menuType !== 'button')); } finally { db.close(); } }
module.exports = { createMenu, deleteMenu, getMenu: (menuId) => { const db = openDatabase(); try { return getMenuDb(db, id(menuId)); } finally { db.close(); } }, getUserMenus, listMenus, setMenuStatus, updateMenu };
