const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'charcoal-user-role-'));
process.env.DATA_DIR = path.join(tmpDir, 'data'); process.env.SQLITE_PATH = path.join(process.env.DATA_DIR, 'users.sqlite');
process.env.UPLOADS_DIR = path.join(tmpDir, 'uploads'); process.env.BACKUPS_DIR = path.join(tmpDir, 'backups'); process.env.CHARCOAL_ADMIN_PASSWORD = 'AdminPassword123!';
const { initDatabase } = require('../db/database');
const { createUser, assignUserRoles, deleteUser, resetUserPassword } = require('../services/userService');
const { login } = require('../services/authService');
const { openDatabase } = require('../db/database');
const { createRole, assignRoleMenus, deleteRole, listRoles } = require('../services/roleService');
const { listMenus } = require('../services/menuService');
try {
  initDatabase();
  const role = createRole({ roleCode: 'auditor', roleName: '审计员' });
  const profileMenu = listMenus().rows.find((item) => item.permissionCode === 'system:profile:update');
  const assignedRole = assignRoleMenus(role.id, [profileMenu.id]);
  assert.deepStrictEqual(assignedRole.menuIds, [profileMenu.id]);
  const user = createUser({ username: 'auditor1', displayName: '审计员一号', password: 'Password123!', roleIds: [role.id] });
  assert.strictEqual(user.roles[0].roleCode, 'auditor');
  assert.throws(() => deleteRole(role.id), (error) => error.details && error.details.code === 'ROLE_HAS_USERS');
  const ordinaryRole = listRoles().rows.find((item) => item.roleCode === 'user');
  const reassigned = assignUserRoles(user.id, [ordinaryRole.id]);
  assert.strictEqual(reassigned.roles[0].roleCode, 'user');
  const previousSession = login({ username: 'auditor1', password: 'Password123!' });
  assert(previousSession.token);
  const reset = resetUserPassword(user.id, { newPassword: 'ChangedPassword123!' });
  assert.strictEqual(reset.user.id, user.id);
  assert.strictEqual(reset.revokedSessionCount, 1, '重置密码必须撤销目标用户既有会话。');
  assert.throws(() => login({ username: 'auditor1', password: 'Password123!' }), (error) => error.code === 'INVALID_CREDENTIALS');
  assert(login({ username: 'auditor1', password: 'ChangedPassword123!' }).token);
  const auditDb = openDatabase();
  const resetLog = auditDb.prepare("SELECT detail_json AS detailJson FROM sys_operation_logs WHERE operation = 'system.user.reset-password'").get();
  auditDb.close();
  assert.strictEqual(resetLog, undefined, '服务层不应自行记录明文密码审计。');
  assert.throws(() => deleteUser(user.id), (error) => error.details && error.details.code === 'USER_HAS_ASSOCIATIONS');
  console.log('user role service tests passed');
} finally { fs.rmSync(tmpDir, { recursive: true, force: true }); }
